name: packman

on:
  push:
    branches:
    - main

jobs:
  build_test_packman_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Displaying a message
        run: echo "Ready!"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: packman:latest
          outputs: type=docker,dest=/tmp/packman.tar

      #- name: RunTrivy
      #  uses: aquasecurity/trivy-action@master
      #  with:
      #    image-ref: 'primary_packman'
      #    format: 'table'
      #    exit-code: '1'
      #    ignore-unfixed: true
      #    vuln-type: 'os,library'
      #    severity: 'CRITICAL'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: packman
          path: /tmp/packman.tar

  push_image:
    runs-on: ubuntu-latest
    needs: build_test_packman_image
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: packman
          path: /tmp

      - name: Push to Docker Hub
        run: docker tag packman profmenko1979/packman:latest
        #run: docker push profmenko1979/packman:latest


      

