name: packman

on:
  push:
    branches:
    - main

jobs:
  building image:
    runs-on: ubuntu-latest
    steps:
      - name: Displaying a message
        run: echo "Ready!"

      - name: CreateImage
        uses: actions/checkout@v2
        run: docker image build -t primary_packman .

