name: packman

on:
  push:
    branches:
    - main

jobs:
  build_packman_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Displaying a message
        run: echo "Ready!"

      - name: CreateImage
        run: docker image build -t primary_packman .

  test_image:
    runs-on: ubuntu-latest
    steps:
      - name: RunTrivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'primary_packman'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

  push_image:
    runs-on: ubuntu-latest
    needs: test_image
    steps:
      - name: Login to Docker Hub
        needs: Run Trivy vulnerability scanner
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push To Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/primary_packman


      

